name: Secret Scanner
on: pull_request
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Scanner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci

      - name: Run Gitleaks Diff Scan
        run: npm run scan:all
